import type { Metadata } from "next";
import "./globals.css";
import { vietnamFont } from "./ui/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html  suppressHydrationWarning={true}  lang="en">
      <body
        className={` ${vietnamFont.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
